environment:
  nodejs_version: "18"

branches:
  only:
    - main

cache: node_modules  # кеширование

install:
  - chdir backend
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run dev
