version: 1.0.{build}

image: Ubuntu1804

environment:
  nodejs_version: "18"

install:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
  - source ~/.nvm/nvm.sh
  - export nodejs_version="18"
  - nvm install $env:nodejs_version
  - node --version
  - npm install -g npm
  - cd backend
  - npm install

build_script:
  - cd $APPVEYOR_BUILD_FOLDER/backend
  - npm run dev

deploy_script:
  - git config --global credential.helper store
  - git config --global user.name AppVeyor
  - git config --global user.email ci@appveyor.com
  - echo "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials"
  - npx push-dir --dir=dist --branch=main --force --verbose
