environment:
  nodejs_version: "18"

branches:
  only:
    - main

cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build   # команда сборки
  - cd backend/
  - npm run dev
